services:
  web:
    container_name: scrape_article
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ../../result:/result
      - ../../logs:/logs
    stdin_open: true   
    tty: true   